### ISSUE TITLE
Telnet timeout

### ISSUE THREAD

**Issue by mrlayance** [ollyg/Net-Appliance-Session#20]
Issue I am running into with a few devices (maybe more).  The device says the script has been completed successfully but not the case.  This all I get from debug.

[   0.012464] pr finding prompt
[   0.016593] tr creating Net::Telnet wrapper for telnet
[   0.017859] tr connecting with:  telnet Host 10.xx.xx.xx Port 23

Thanks

**Comment by ollyg** [comment]
Try a tcpdump? If the script is stopping at the initial connect then it would appear to be a network timeout.
