### ISSUE TITLE
Variable "$VERSION" is not imported at /usr/local/share/perl/5.26.1/Net/Appliance/Session

### ISSUE THREAD

**Issue by igoryonya** [ollyg/Net-Appliance-Session#25]
$ nas --help
Variable "$VERSION" is not imported at /usr/local/share/perl/5.26.1/Net/Appliance/Session/Scripting.pm line 22.
Compilation failed in require at /usr/local/bin/nas line 6.
BEGIN failed--compilation aborted at /usr/local/bin/nas line 6.

**Comment by ollyg** [comment]
Hi, this is now fixed in the next release. Sorry for the error.
